# -*- coding: utf-8 -*-
"""ejercicios.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ebFmcTg_pvXaCtocnPZagWs2u1zNvH9
"""

"""
1.	Haga un programa que calcule el porcentaje de alumnos perdidos y de alumnos que ganaron.

2.	Haga un programa que calcule el valor de un computador si es día de descuento.
3.	Haga un programa que calcule el salario básico para un empleado sabiendo que el
 empleado gana un salario bruto, a ese salario bruto se le descuenta el 10% por
  la retención en la fuente, 1% para Sena, 1% para icbf y 2% por estampilla.
   Y sobre el valor resultante se le descuenta el 0.4%  correspondiente al 4*1000.

4.	Haga un programa de dados dos numero diga cuál es el mayor
5.	Haga un programa que calcule el promedio de notas para 3 notas. 
 Si el promedio es menor a 3 aparezca un mensaje el estudiante perdió 
 en caso contrario diga el estudiante gano.

 import statistics

def f(nota1, nota2, nota3):
  notas = [nota1, nota2, nota3]
  promedioNotas = sum(notas) / len(notas) #sumatoriadatos / cantidaddedatos

  if promedioNotas < 3:
    return print('El estudiante perdió la asignatura.')
  else:
    return print('El estudiante ganó la asignatura.')

nota1 = float(input('Ingrese la Nota 1. '))
nota2 = float(input('Ingrese la Nota 2. '))
nota3 = float(input('Ingrese la Nota 3. '))

f(nota1, nota2, nota3)

6.	Haga un programa que calcule el promedio de notas para 3 notas. 
 Si el promedio es menor a tres aparezca un mensaje el estudiante perdió, 
 si el promedio es mayor o igual a tres y menor que cuatro aparezca  un mensaje bien es estudiante gano,
 si el promedio es mayor o igual a cuatro el mensaje diga excelente promedio superior. 

 7.	Haga un programa que dado un número, si este es mayor que 30 calcule el cubo, en caso contrario calcule el cuadrado.
8.	Haga un programa que calcule el salario neto de un empleado sabiendo que el salario básico de él
 se calcula de acuerdo a número de horas trabajadas y la hora tiene un valor especifico, además si ese salario 
 es menor que dos salarios mínimos legales vigente (smlv) se le paga un subsidio de transporte equivalente a 55000.  (el smlv=565000).

def alumnos(a,r):
  aprobado = (a*100)/100
  reprobado = (r*100)/100
  return print(f" porcentaje aprobado : {aprobado}\n porcentaje reprobado : {reprobado}")
a = float(input("Cantidad de alumnos aprobados :\n")) 
r = float(input("Cantidad de alumnos reprobados :\n"))   
alumnos(a,r)
__________________________________________________________________

#2.	Haga un programa que calcule el valor de un computador si es día de descuento.

def descuento(precio,d):
  if d == "lunes":
    precio *20+precio
    return print(f"tienes un descuento del 20% , el valor a cancelar es : {precio}")
  else: 
    precio=precio
    return print(f"el valor a pagar es :{precio}")
precio = float(input("valor del articulo :\n"))
d = input("dia: \n")    
descuento(precio,d)
________________________________
4.	Haga un programa de dados dos numero diga cuál es el mayor

def mayorQue(a,b):
  if a > b:
    return print(f" {a} es mayor que {b}")
  elif b > a:
    return print(f" {b} es mayor que {a}")
  elif a == b: 
    return print("son iguales")
a = int(input("primer numero : "))  
b = int(input("segundo numero : "))
mayorQue(a,b)

#5.	Haga un programa que calcule el promedio de notas para 3 notas. 
 #Si el promedio es menor a 3 aparezca un mensaje el estudiante perdió 
 #en caso contrario diga el estudiante gano.
 
def notas(a,b,c):
  nota=(a+b+c)//3
  if nota < 3:
    return print(f"perdio la materia su promedio fue: {nota}")
  else:
    return print(f"aprobo la materia su promedio fue: {nota}")

  
a = float(input("primer nota :\n"))  
b = float(input("segunda nota :\n")) 
c = float(input("tercer nota :\n"))
notas(a,b,c)


#6.	Haga un programa que calcule el promedio de notas para 3 notas. 
 #Si el promedio es menor a tres aparezca un mensaje el estudiante perdió, 
 #si el promedio es mayor o igual a tres y menor que cuatro aparezca  un mensaje bien es estudiante gano,
 #si el promedio es mayor o igual a cuatro el mensaje diga excelente promedio superior. 

def notas(a,b,c):
  nota=(a+b+c)//3
  if nota < 3:
    return print(f"El estudiante perdio la materia, su promedio fue: {nota}")
  elif nota >= 3 and nota < 4:
    return print(f"bien es estudiante gano su promedio fue: {nota}")
  elif nota >= 4:
    return print(f"excelente promedio superior, su promedio fue: {nota}")
  
a = float(input("primer nota :\n"))  
b = float(input("segunda nota :\n")) 
c = float(input("tercer nota :\n"))
notas(a,b,c)


#__________________________________________________________________________
#7.	Haga un programa que dado un número, si este es mayor que 30 calcule el cubo, en caso contrario calcule el cuadrado.
def num(x):
  if x > 30:
    valor = x**3
    return print(f"el cubo de {x} es :{valor}")
  else:
    valor = x*x
    return print(f"el cuadrado de {x} es :{valor}")
x = float(input("Ingrese un numero :\n"))
num(x)

"""
#8.	Haga un programa que calcule el salario neto de un empleado sabiendo que el salario básico de él
 #se calcula de acuerdo a número de horas trabajadas y la hora tiene un valor especifico, además si ese salario 
 #es menor que dos salarios mínimos legales vigente (smlv) se le paga un subsidio de transporte equivalente a 55000.  (el smlv=565000).
def salario(horas,valor_hora):
  smlv=565000
  sueldo = horas*valor_hora
  if sueldo < (smlv*2):
    sueldo = sueldo+55000
    return print(f"su salario es : ${sueldo}")
  else:
    return print(f"su salario es : ${sueldo}")
horas = int(input("Horas trabajadas :\n"))
valor_hora = int(input("Valor en pesos por hora :\n"))    
salario(horas,valor_hora)   


"""
9 Haga un programa que calcule el valor de un computador sabiendo que tienen un 
precio de venta y se hace un descuento dependiendo de la forma de pago, si es efectivo
 se le descuenta 30% del valor venta, si es con tarjeta crédito se le descuenta 15%
  del valor venta y si es con tarjeta debito se le descuenta un 25% del valor venta.

  
"""

def precio(valor,medio_pago):
  efectivo = ""
  credito = ""
  debito = ""
  if medio_pago == "efectivo":
    descuento = valor*0.30
    valor = valor-descuento
    return print(f"Obtubo un descuento de {descuento} el valor a cancelar es : {valor}")
  elif medio_pago == "credito":
     descuento = valor*0.15
     valor = valor-descuento
     return print(f"Obtubo un descuento de {descuento} el valor a cancelar es : {valor}")
  elif medio_pago == "debito":
    descuento = valor*0.25
    valor = valor-descuento
    return print(f"Obtubo un descuento de {descuento} el valor a cancelar es : {valor}")
valor = float(input("Ingrese el valor del computador :\n"))  
medio_pago = input("Ingrese el medio de pago :\n") 
precio(valor,medio_pago) 

#10 Haga un programa que dados tres números diga cual es el mayor.

def num(a,b,c):
  if a > b and a > c:
    return print(f"{a} es el numero mayor ")
  elif b > a and b > c:
    return print(f"{b} es el numero mayor ")
  elif c > a and c > b:
    return print(f"{c} es el numero mayor ")
a = int(input("primer numero :")) 
b = int(input("segundo numero :")) 
c = int(input("tercer numero :")) 
num(a,b,c)